#############################
# For the sphere collisions #
#############################

# x0:
#   thumb: [1.19, 1.21, 0.56, 0.67]
#   index: [0.0, 1.21, 0.43, 0.57]
#   middle: [0.0, 1.21, 0.43, 0.57]
#   ring: [0.0, 1.21, 0.43, 0.57]

# xa_reg:
#   thumb: [1.0, 1.2, 0.93, 0.84]
#   index: [0.0, 0.95, 1.0, 0.57]
#   middle: [0.0, 0.95, 1.0, 0.57]
#   ring: [0.0, 0.95, 1.0, 0.57]

#############################
# For the cuboid collisions #
#############################

obj_joint_name: "cube_root_joint"

jnames:
  thumb: [12, 13, 14, 15]
  index: [1, 0, 2, 3]
  middle: [5, 4, 6, 7]
  ring: [9, 8, 10, 11]

x0:
  # thumb: [0.33, 1.39, 1.25, 1.22]
  thumb: [0.33, 1.8, 1.25, 1.22]
  index: [0.78, -0.38, 0.49, 0.87]
  middle: [0.03, 0.0, 1.31, 1.22]
  ring: [0.78, 0.38, 0.49, 0.87]

xa_reg:
  # thumb: [0.33, 1.39, 1.25, 1.22]
  thumb: [0.33, 1.8, 1.25, 1.22]
  index: [0.78, -0.38, 0.49, 0.87]
  middle: [0.03, 0.0, 1.31, 1.22]
  ring: [0.78, 0.38, 0.49, 0.87]

dyaw: 0.07853

u_lb: -0.08
u_ub: 0.08