#############################
# For the sphere collisions #
#############################

# x0:
#   thumb: [1.19, 1.21, 0.56, 0.67]
#   index: [0.0, 1.21, 0.43, 0.57]
#   middle: [0.0, 1.21, 0.43, 0.57]
#   ring: [0.0, 1.21, 0.43, 0.57]

# xa_reg:
#   thumb: [1.0, 1.2, 0.93, 0.84]
#   index: [0.0, 0.95, 1.0, 0.57]
#   middle: [0.0, 0.95, 1.0, 0.57]
#   ring: [0.0, 0.95, 1.0, 0.57]

#############################
# For the cuboid collisions #
#############################

obj_joint_name: "cylinder_root_joint"

jnames:
  thumb: [12, 13, 14, 15]
  index: [1, 0, 2, 3]
  middle: [5, 4, 6, 7]
  ring: [9, 8, 10, 11]

x0:
  # -------- obj1 --------
  thumb: [0.55, 1.51, 0.61, 1.3]
  index: [0.51, -0.64, 1.3, 0.72]
  middle: [0.42, 0.0, 0.85, 0.88]
  ring: [0.56, 0.76, 1.35, 0.61]
  # ----------------------

  # -------- obj2 --------
  # thumb: [0.55, 1.46, 0.71, 1.3]
  # index: [0.56, -0.78, 1.33, 0.72]
  # middle: [0.42, 0.0, 0.85, 0.88]
  # ring: [0.51, 0.76, 1.27, 0.61]
  # ----------------------

  # -------- obj3 --------
  # thumb: [0.53, 1.38, 0.71, 1.3]
  # index: [0.62, -0.53, 1.51, 0.39]
  # middle: [0.71, 0.0, 0.85, 0.88]
  # ring: [0.75, 0.53, 1.51, 0.39]
  # ----------------------

  # -------- obj4 --------
  # thumb: [0.28, 1.73, 0.71, 1.3]
  # index: [0.64, -0.78, 1.15, 0.39]
  # middle: [0.27, 0.0, 0.85, 0.88]
  # ring: [0.67, 0.67, 1.17, 0.23]
  # ----------------------

xa_reg:
  # -------- obj1 --------
  thumb: [0.55, 1.51, 0.61, 1.3]
  index: [0.51, -0.64, 1.3, 0.72]
  middle: [0.42, 0.0, 0.85, 0.88]
  ring: [0.56, 0.76, 1.35, 0.61]
  # ----------------------

  # -------- obj2 --------
  # thumb: [0.55, 1.46, 0.71, 1.3]
  # index: [0.56, -0.78, 1.33, 0.72]
  # middle: [0.42, 0.0, 0.85, 0.88]
  # ring: [0.51, 0.76, 1.27, 0.61]
  # ----------------------

  # -------- obj3 --------
  # thumb: [0.53, 1.38, 0.71, 1.3]
  # index: [0.62, -0.53, 1.51, 0.39]
  # middle: [0.71, 0.0, 0.85, 0.88]
  # ring: [0.75, 0.53, 1.51, 0.39]
  # ----------------------

  # -------- obj4 --------
  # thumb: [0.28, 1.73, 0.71, 1.3]
  # index: [0.64, -0.78, 1.15, 0.39]
  # middle: [0.27, 0.0, 0.85, 0.88]
  # ring: [0.67, 0.67, 1.17, 0.23]
  # ----------------------


dyaw: 0.07853

u_lb: -0.08
u_ub: 0.08