#############################
# For the sphere collisions #
#############################

# x0:
#   thumb: [1.19, 1.21, 0.56, 0.67]
#   index: [0.0, 1.21, 0.43, 0.57]
#   middle: [0.0, 1.21, 0.43, 0.57]
#   ring: [0.0, 1.21, 0.43, 0.57]

# xa_reg:
#   thumb: [1.0, 1.2, 0.93, 0.84]
#   index: [0.0, 0.95, 1.0, 0.57]
#   middle: [0.0, 0.95, 1.0, 0.57]
#   ring: [0.0, 0.95, 1.0, 0.57]

#############################
# For the cuboid collisions #
#############################

obj_joint_name: "valve_root_joint"

jnames:
  thumb: [12, 13, 14, 15]
  index: [1, 0, 2, 3]
  middle: [5, 4, 6, 7]
  ring: [9, 8, 10, 11]

x0:
  # ------ for one-shaped valve ------
  # thumb: [1.47, 0.66, -0.17, 1.16]
  # index: [0.5, -0.21, 1.02, 0.39]
  # middle: [0.62, 0.0, 0.63, 0.78]
  # ring: [0.5, 0.21, 1.02, 0.39]

  # ------ for cross-shaped valve ------
  thumb: [1.31, 0.75, -0.17, 1.16]
  index: [0.72, -0.19, 0.7, 0.41]
  middle: [0.15, 0.0, 0.86, 0.78]
  ring: [0.72, 0.19, 0.7, 0.41]

xa_reg:
  # ------ for one-shaped valve ------
  # thumb: [1.1, 1.29, 0.0, 1.7]
  # index: [0.15, -0.21, 0.96, 0.91]
  # middle: [0.12, 0.0, 0.99, 0.78]
  # ring: [0.15, 0.21, 0.96, 0.91]

  # ------ for cross-shaped valve ------
  thumb: [1.31, 0.75, -0.17, 1.16]
  index: [0.72, -0.19, 0.7, 0.41]
  middle: [0.15, 0.0, 0.86, 0.78]
  ring: [0.72, 0.19, 0.7, 0.41]

xa_reg2:
  # ------ for one-shaped valve ------
  # thumb: [1.47, 0.7, -0.03, 0.92]
  # index: [0.7, -0.21, 0.76, 0.38]
  # middle: [0.79, 0.0, 0.47, 0.65]
  # ring: [0.7, 0.21, 0.76, 0.38]

  # ------ for cross-shaped valve ------
  thumb: [1.52, 1.22, -0.61, 1.88]
  index: [0.42, -0.35, 1.12, 0.88]
  middle: [0.66, 0.0, 0.47, 0.67]
  ring: [0.42, 0.35, 1.12, 0.88]

dyaw: 0.07853

u_lb: -0.08
u_ub: 0.08