mujoco_ros:
  ros__parameters:
    contact_geom_names:
      - leap_hand_right::fingertip_collision
      - leap_hand_right::fingertip_2_collision
      - leap_hand_right::fingertip_3_collision
      - leap_hand_right::thumb_fingertip_collision
