obj_joint_name: "cylinder_root_joint"

jnames:
  thumb: [12, 13, 14, 15]
  index: [1, 0, 2, 3]
  middle: [5, 4, 6, 7]
  ring: [9, 8, 10, 11]

x0:
  # -------- obj0 (normal cylinder) --------
  # thumb: [1.39, 0.94, -0.37, 0.66]
  # index: [0.54, -1.05, 1.35, 0.2]
  # middle: [0.62, 0.0, 0.73, 0.45]
  # ring: [0.54, 1.05, 1.35, 0.2]
  # ----------------------------------------

  # -------- obj1 --------
  thumb: [0.55, 1.51, 0.61, 1.3]
  index: [0.51, -0.64, 1.3, 0.72]
  middle: [0.42, 0.0, 0.85, 0.88]
  ring: [0.56, 0.76, 1.35, 0.61]
  # ----------------------

  # -------- obj2 --------
  # thumb: [0.55, 1.46, 0.71, 1.3]
  # index: [0.56, -0.78, 1.33, 0.72]
  # middle: [0.42, 0.0, 0.85, 0.88]
  # ring: [0.51, 0.76, 1.27, 0.61]
  # ----------------------

  # -------- obj3 --------
  # thumb: [0.53, 1.38, 0.71, 1.3]
  # index: [0.62, -0.53, 1.51, 0.39]
  # middle: [0.71, 0.0, 0.85, 0.88]
  # ring: [0.75, 0.53, 1.51, 0.39]
  # ----------------------

  # -------- obj4 --------
  # thumb: [0.28, 1.73, 0.71, 1.3]
  # index: [0.64, -0.78, 1.15, 0.39]
  # middle: [0.27, 0.0, 0.85, 0.88]
  # ring: [0.67, 0.67, 1.17, 0.23]
  # ----------------------

xa_reg:
  # -------- obj0 (normal cylinder) --------
  # thumb: [1.39, 0.94, -0.37, 0.66]
  # index: [0.54, -1.05, 1.35, 0.2]
  # middle: [0.62, 0.0, 0.73, 0.45]
  # ring: [0.54, 1.05, 1.35, 0.2]
  # ----------------------

  # -------- obj1 --------
  thumb: [0.55, 1.51, 0.61, 1.3]
  index: [0.51, -0.64, 1.3, 0.72]
  middle: [0.42, 0.0, 0.85, 0.88]
  ring: [0.56, 0.76, 1.35, 0.61]
  # ----------------------

  # -------- obj2 --------
  # thumb: [0.55, 1.46, 0.71, 1.3]
  # index: [0.56, -0.78, 1.33, 0.72]
  # middle: [0.42, 0.0, 0.85, 0.88]
  # ring: [0.51, 0.76, 1.27, 0.61]
  # ----------------------

  # -------- obj3 --------
  # thumb: [0.53, 1.38, 0.71, 1.3]
  # index: [0.62, -0.53, 1.51, 0.39]
  # middle: [0.71, 0.0, 0.85, 0.88]
  # ring: [0.75, 0.53, 1.51, 0.39]
  # ----------------------

  # -------- obj4 --------
  # thumb: [0.28, 1.73, 0.71, 1.3]
  # index: [0.64, -0.78, 1.15, 0.39]
  # middle: [0.27, 0.0, 0.85, 0.88]
  # ring: [0.67, 0.67, 1.17, 0.23]
  # ----------------------

#############################
#     Other parameters      #
#############################

model_url: 'leap_3d_zrot_any_cylinder.yml'

nq: 17
nv: 17
nu: 16
nc: 4

q_u_indices: [0]
dxu: 0.07853
target_xu: 3.18
use_target_xu: true
u_lb: -0.08
u_ub: 0.08

high_level_frequency: 10
ddp_execution_scale: 0.5      # 0.5
force_threshold: 3.0          # N
desired_force_scale: 1.0     # 1.0

object_dofs:
  task_spec: 'leap_3d_zrot_any_cylinder'
  xyz: []     #
  rpy: ['rz']    # rz

ddp_params:
  h: 0.1
  kappa: 100
  kappa_exact: 10000
  T_trajopt: 40
  T_ctrl: 10
  auto_diff: false
  finger_link_names:
    - fingertip
    - fingertip_2
    - fingertip_3
    - thumb_fingertip
  object_link_name: cylinder_link

  # weights (mpc)
  w_u: 1e1
  w_a: [1e-1, 1e-1]
  w_uT: 1e2
  w_aT: 5e2

  # weights (trajopt)
  TO_w_u: 1e1
  TO_w_a: 1e-2
  TO_w_uT: 1e2
  TO_w_aT: 1e0
  TO_W_x: 1
  TO_W_u: 0.04
  TO_W_xT: 1

  # weights (cost sum)
  W_X: 1          # stateReg
  W_U: 0.04       # controlReg
  W_SC: 0       # selfCollide
  W_J: 0          # jointLimits
  model_url_sc: ''

  warmstart_suffix: cylinder_leap
